import Link from "next/link";
import { unstable_noStore as noStore } from "next/cache";
import { Anchor, BarChart3, Camera, Check, ChevronRight, CloudSun, Fish, Menu, ShieldCheck, Ship, Sparkles, Waves } from "lucide-react";

export const dynamic = "force-dynamic";
export const revalidate = 0;

export default function HomePage() {
  noStore();
  return <div className="landing">
    <div className="landing-nav-shell"><header className="landing-nav"><Link href="/" className="brand"><img className="brand-logo-full" src="/gofishing-logo.svg" alt="GoFishing.mx" /></Link><nav><Link href="/comunidad">Comunidad</Link><a href="#beneficios">Beneficios</a><a href="#privacidad">Privacidad</a></nav><div><Link className="button secondary" href="/iniciar-sesion">Iniciar sesión</Link><Link className="button primary" href="/registro">Crear cuenta</Link></div><details className="landing-mobile-menu"><summary aria-label="Abrir menú"><Menu size={20} /></summary><div><Link href="/">Inicio</Link><Link href="/comunidad">Comunidad</Link><Link href="/iniciar-sesion">Iniciar sesión</Link><Link href="/registro">Crear cuenta</Link></div></details></header></div>
    <main><section className="landing-hero"><div className="hero-copy"><span className="hero-pill"><Sparkles size={15} />Tu bitácora personal del mar</span><h1>Tu historial de pesca,<br /><em>siempre contigo.</em></h1><p>Registra tus salidas, capturas, fotografías y récords personales en una bitácora hecha para pescadores.</p><div className="hero-actions"><Link className="button primary large" href="/registro">Comenzar mi bitácora <ChevronRight size={19} /></Link><Link className="button secondary large" href="/iniciar-sesion">Iniciar sesión</Link></div><small><ShieldCheck size={15} />Gratis · Privado</small></div><div className="hero-visual"><div className="sun" /><div className="wave wave-a" /><div className="wave wave-b" /><div className="boat"><Ship /></div><div className="dashboard-preview"><div className="preview-top"><span><Fish />GoFishing.mx</span><i /><i /></div><div className="preview-body"><div className="preview-sidebar"><i /><i /><i /><i /></div><div className="preview-content"><small>BUEN DÍA, DAVID</small><h3>Tu bitácora</h3><div className="preview-stats"><span><b>12</b><small>Pescas</small></span><span><b>38</b><small>Peces</small></span><span><b>94 kg</b><small>Peso</small></span><span><b><CloudSun size={16} /></b><small>Consulta el clima de tu pesca</small></span></div><div className="preview-chart"><i /><i /><i /><i /><i /><i /></div></div></div></div><div className="floating-catch"><span><Fish /></span><div><small>NUEVO RÉCORD</small><b>Mero · 8.4 kg</b></div><Check /></div></div></section>
      <section className="trust-strip"><span><Anchor /><b>Hecho para</b><small>pescadores de Yucatán</small></span><span><ShieldCheck /><b>Tus datos</b><small>siempre privados</small></span><span><Camera /><b>Tus recuerdos</b><small>bien guardados</small></span><span><CloudSun /><b>Consulta el clima</b><small>de tu próxima pesca</small></span></section>
      <section id="beneficios" className="benefits"><div className="section-heading"><span className="eyebrow">TODO EN UN SOLO LUGAR</span><h2>Cada salida cuenta una historia</h2><p>GoFishing.mx hace fácil recordar cada detalle sin quitarte tiempo para disfrutar el mar.</p></div><div className="benefit-grid"><Benefit icon={Ship} title="Guarda cada salida" body="Fecha, puerto, embarcación y notas en un registro rápido y claro." /><Benefit icon={Fish} title="Registra tus peces" body="Especie, peso, longitud, señuelo y si fue liberado o conservado." /><Benefit icon={BarChart3} title="Descubre tus números" body="Visualiza tus puertos favoritos, especies frecuentes y récords." /><Benefit icon={Camera} title="Conserva recuerdos" body="Añade fotografías privadas de cada captura y revive la aventura." /></div></section>
      <section id="privacidad" className="responsibility"><div><span><Waves /></span><div><span className="eyebrow">PESCA RESPONSABLE</span><h2>El mar se disfruta y se respeta</h2><p>GoFishing.mx es una bitácora personal y no sustituye la información oficial. Consulta permisos, vedas, tallas, límites y regulaciones aplicables antes de cada salida.</p></div><a href="https://www.gob.mx/conapesca" target="_blank" rel="noreferrer" className="button secondary">Consultar fuentes oficiales <ChevronRight size={17} /></a></div></section>
    </main><footer className="landing-footer"><div className="brand"><img className="brand-logo-full" src="/gofishing-logo.svg" alt="GoFishing.mx" /></div><p>Hecho con respeto por el mar y sus historias.</p><nav><Link href="/privacidad">Privacidad</Link><Link href="/terminos">Términos</Link></nav></footer>
  </div>;
}

function Benefit({ icon: Icon, title, body }: { icon: typeof Fish; title: string; body: string }) { return <article><span><Icon /></span><h3>{title}</h3><p>{body}</p><i><ChevronRight /></i></article>; }
