import {
  bigint,
  char,
  double,
  int,
  mysqlTable,
  text,
  uniqueIndex,
  varchar,
} from "drizzle-orm/mysql-core";

export const profiles = mysqlTable(
  "profiles",
  {
    email: varchar("email", { length: 255 }).primaryKey(),
    displayName: varchar("display_name", { length: 255 }).notNull(),
    firstName: varchar("first_name", { length: 255 }).notNull().default(""),
    lastName: varchar("last_name", { length: 255 }).notNull().default(""),
    city: varchar("city", { length: 255 }).notNull().default(""),
    state: varchar("state", { length: 255 }).notNull().default("Yucatán"),
    country: varchar("country", { length: 255 }).notNull().default("México"),
    timezone: varchar("timezone", { length: 100 }).notNull().default("America/Merida"),
    weightUnit: varchar("weight_unit", { length: 16 }).notNull().default("kg"),
    role: varchar("role", { length: 16 }).notNull().default("USER"),
    status: varchar("status", { length: 16 }).notNull().default("ACTIVE"),
    passwordHash: text("password_hash"),
    publicSlug: varchar("public_slug", { length: 255 }),
    publicProfileEnabled: int("public_profile_enabled").notNull().default(1),
    avatarUrl: text("avatar_url"),
    createdAt: varchar("created_at", { length: 64 }).notNull(),
    updatedAt: varchar("updated_at", { length: 64 }).notNull(),
  },
  (table) => [uniqueIndex("profiles_public_slug_unique").on(table.publicSlug)],
);

export const fishingTrips = mysqlTable("fishing_trips", {
  id: char("id", { length: 36 }).primaryKey(),
  ownerEmail: varchar("owner_email", { length: 255 }).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  port: varchar("port", { length: 255 }).notNull(),
  departureLocationId: char("departure_location_id", { length: 36 }),
  fishingDate: varchar("fishing_date", { length: 32 }).notNull(),
  departureTime: varchar("departure_time", { length: 32 }),
  returnTime: varchar("return_time", { length: 32 }),
  area: varchar("area", { length: 255 }),
  vessel: varchar("vessel", { length: 255 }),
  captain: varchar("captain", { length: 255 }),
  notes: text("notes"),
  status: varchar("status", { length: 16 }).notNull().default("DRAFT"),
  coverImageUrl: text("cover_image_url"),
  publicShare: int("public_share").notNull().default(0),
  createdAt: varchar("created_at", { length: 64 }).notNull(),
  updatedAt: varchar("updated_at", { length: 64 }).notNull(),
  deletedAt: varchar("deleted_at", { length: 64 }),
});

export const catches = mysqlTable("catches", {
  id: char("id", { length: 36 }).primaryKey(),
  tripId: char("trip_id", { length: 36 }).notNull(),
  ownerEmail: varchar("owner_email", { length: 255 }).notNull(),
  species: varchar("species", { length: 255 }).notNull(),
  customSpecies: int("custom_species").notNull().default(0),
  weightKg: double("weight_kg").notNull(),
  originalWeight: double("original_weight").notNull(),
  originalUnit: varchar("original_unit", { length: 16 }).notNull(),
  releaseStatus: varchar("release_status", { length: 32 }).notNull().default("UNSPECIFIED"),
  lengthCm: double("length_cm"),
  caughtAt: varchar("caught_at", { length: 64 }),
  lure: varchar("lure", { length: 255 }),
  notes: text("notes"),
  createdAt: varchar("created_at", { length: 64 }).notNull(),
  updatedAt: varchar("updated_at", { length: 64 }).notNull(),
  deletedAt: varchar("deleted_at", { length: 64 }),
});

export const mediaAssets = mysqlTable("media_assets", {
  id: char("id", { length: 36 }).primaryKey(),
  ownerEmail: varchar("owner_email", { length: 255 }).notNull(),
  tripId: char("trip_id", { length: 36 }),
  catchId: char("catch_id", { length: 36 }),
  storageKey: varchar("storage_key", { length: 768 }).notNull(),
  mimeType: varchar("mime_type", { length: 128 }).notNull(),
  sizeBytes: bigint("size_bytes", { mode: "number" }).notNull(),
  altText: text("alt_text"),
  createdAt: varchar("created_at", { length: 64 }).notNull(),
  deletedAt: varchar("deleted_at", { length: 64 }),
});

export const species = mysqlTable(
  "species",
  {
    id: char("id", { length: 36 }).primaryKey(),
    commonName: varchar("common_name", { length: 255 }).notNull(),
    aliases: text("aliases").notNull(),
    scientificName: varchar("scientific_name", { length: 255 }),
    slug: varchar("slug", { length: 255 }).notNull(),
    iconKey: varchar("icon_key", { length: 64 }).notNull().default("fish"),
    sortOrder: int("sort_order").notNull().default(0),
    active: int("active").notNull().default(1),
  },
  (table) => [uniqueIndex("species_slug_unique").on(table.slug)],
);

export const ports = mysqlTable(
  "ports",
  {
    id: char("id", { length: 36 }).primaryKey(),
    name: varchar("name", { length: 255 }).notNull(),
    slug: varchar("slug", { length: 255 }).notNull(),
    type: varchar("type", { length: 32 }).notNull().default("PUERTO"),
    municipality: varchar("municipality", { length: 255 }),
    state: varchar("state", { length: 255 }).notNull().default("Yucatán"),
    stateCode: varchar("state_code", { length: 16 }).notNull().default("YUC"),
    country: varchar("country", { length: 255 }).notNull().default("México"),
    countryCode: varchar("country_code", { length: 16 }).notNull().default("MX"),
    latitude: double("latitude"),
    longitude: double("longitude"),
    marineLatitude: double("marine_latitude"),
    marineLongitude: double("marine_longitude"),
    timezone: varchar("timezone", { length: 100 }).notNull().default("America/Merida"),
    isWeatherEnabled: int("is_weather_enabled").notNull().default(0),
    tideCheckEnabled: int("tide_check_enabled").notNull().default(0),
    tideCheckStationId: varchar("tide_check_station_id", { length: 128 }),
    tideCheckStationName: varchar("tide_check_station_name", { length: 255 }),
    tideCheckStationLatitude: double("tide_check_station_latitude"),
    tideCheckStationLongitude: double("tide_check_station_longitude"),
    tideCheckStationState: varchar("tide_check_station_state", { length: 255 }),
    tideCheckStationCountry: varchar("tide_check_station_country", { length: 255 }),
    stationVerifiedAt: varchar("station_verified_at", { length: 64 }),
    stationVerifiedBy: varchar("station_verified_by", { length: 255 }),
    sortOrder: int("sort_order").notNull().default(0),
    active: int("active").notNull().default(1),
    createdAt: varchar("created_at", { length: 64 }).notNull().default(""),
    updatedAt: varchar("updated_at", { length: 64 }).notNull().default(""),
  },
  (table) => [uniqueIndex("ports_slug_unique").on(table.slug)],
);

export const weatherCache = mysqlTable(
  "weather_cache",
  {
    id: char("id", { length: 36 }).primaryKey(),
    locationId: char("location_id", { length: 36 }).notNull(),
    forecastType: varchar("forecast_type", { length: 64 }).notNull(),
    provider: varchar("provider", { length: 64 }).notNull().default("open-meteo"),
    payloadJson: text("payload_json").notNull(),
    fetchedAt: varchar("fetched_at", { length: 64 }).notNull(),
    expiresAt: varchar("expires_at", { length: 64 }).notNull(),
    staleUntil: varchar("stale_until", { length: 64 }).notNull(),
    createdAt: varchar("created_at", { length: 64 }).notNull(),
    updatedAt: varchar("updated_at", { length: 64 }).notNull(),
  },
  (table) => [
    uniqueIndex("weather_cache_unique").on(
      table.locationId,
      table.forecastType,
      table.provider,
    ),
  ],
);

export const fishingTripWeatherSnapshots = mysqlTable(
  "fishing_trip_weather_snapshots",
  {
    id: char("id", { length: 36 }).primaryKey(),
    fishingTripId: char("fishing_trip_id", { length: 36 }).notNull(),
    locationId: char("location_id", { length: 36 }).notNull(),
    capturedAt: varchar("captured_at", { length: 64 }).notNull(),
    snapshotType: varchar("snapshot_type", { length: 64 }).notNull(),
    provider: varchar("provider", { length: 64 }).notNull(),
    providerModel: varchar("provider_model", { length: 128 }),
    latitude: double("latitude").notNull(),
    longitude: double("longitude").notNull(),
    marineLatitude: double("marine_latitude"),
    marineLongitude: double("marine_longitude"),
    timezone: varchar("timezone", { length: 100 }).notNull(),
    temperatureC: double("temperature_c"),
    apparentTemperatureC: double("apparent_temperature_c"),
    humidityPercent: double("humidity_percent"),
    precipitationMm: double("precipitation_mm"),
    precipitationProbabilityPercent: double("precipitation_probability_percent"),
    weatherCode: int("weather_code"),
    cloudCoverPercent: double("cloud_cover_percent"),
    visibilityMeters: double("visibility_meters"),
    windSpeedKmh: double("wind_speed_kmh"),
    windDirectionDegrees: double("wind_direction_degrees"),
    windGustKmh: double("wind_gust_kmh"),
    waveHeightMeters: double("wave_height_meters"),
    waveDirectionDegrees: double("wave_direction_degrees"),
    wavePeriodSeconds: double("wave_period_seconds"),
    swellHeightMeters: double("swell_height_meters"),
    swellDirectionDegrees: double("swell_direction_degrees"),
    swellPeriodSeconds: double("swell_period_seconds"),
    seaSurfaceTemperatureC: double("sea_surface_temperature_c"),
    oceanCurrentVelocityKmh: double("ocean_current_velocity_kmh"),
    oceanCurrentDirectionDegrees: double("ocean_current_direction_degrees"),
    rawProviderReference: text("raw_provider_reference"),
    createdAt: varchar("created_at", { length: 64 }).notNull(),
  },
  (table) => [
    uniqueIndex("fishing_trip_weather_snapshots_trip_unique").on(table.fishingTripId),
  ],
);

export const fishingConditionThresholds = mysqlTable(
  "fishing_condition_thresholds",
  {
    id: char("id", { length: 36 }).primaryKey(),
    region: varchar("region", { length: 255 }).notNull(),
    maximumFavorableWindKmh: double("maximum_favorable_wind_kmh").notNull(),
    maximumCautionWindKmh: double("maximum_caution_wind_kmh").notNull(),
    maximumFavorableGustKmh: double("maximum_favorable_gust_kmh").notNull(),
    maximumCautionGustKmh: double("maximum_caution_gust_kmh").notNull(),
    maximumFavorableWaveMeters: double("maximum_favorable_wave_meters").notNull(),
    maximumCautionWaveMeters: double("maximum_caution_wave_meters").notNull(),
    minimumFavorableWavePeriodSeconds: double("minimum_favorable_wave_period_seconds").notNull(),
    active: int("active").notNull().default(1),
    updatedAt: varchar("updated_at", { length: 64 }).notNull(),
    updatedBy: varchar("updated_by", { length: 255 }),
  },
  (table) => [uniqueIndex("fishing_condition_thresholds_region_unique").on(table.region)],
);

export const weatherRateLimits = mysqlTable(
  "weather_rate_limits",
  {
    id: char("id", { length: 36 }).primaryKey(),
    rateKey: varchar("rate_key", { length: 255 }).notNull(),
    windowStart: varchar("window_start", { length: 64 }).notNull(),
    count: int("count").notNull().default(1),
    updatedAt: varchar("updated_at", { length: 64 }).notNull(),
  },
  (table) => [uniqueIndex("weather_rate_limits_rate_key_unique").on(table.rateKey)],
);

export const auditLogs = mysqlTable("audit_logs", {
  id: char("id", { length: 36 }).primaryKey(),
  actorEmailHash: varchar("actor_email_hash", { length: 255 }).notNull(),
  action: varchar("action", { length: 128 }).notNull(),
  entityType: varchar("entity_type", { length: 128 }).notNull(),
  entityId: varchar("entity_id", { length: 255 }),
  createdAt: varchar("created_at", { length: 64 }).notNull(),
});

export const accountTokens = mysqlTable(
  "account_tokens",
  {
    id: char("id", { length: 36 }).primaryKey(),
    email: varchar("email", { length: 255 }).notNull(),
    tokenHash: varchar("token_hash", { length: 255 }).notNull(),
    type: varchar("type", { length: 64 }).notNull(),
    pendingEmail: varchar("pending_email", { length: 255 }),
    reason: text("reason"),
    expiresAt: varchar("expires_at", { length: 64 }).notNull(),
    usedAt: varchar("used_at", { length: 64 }),
    createdAt: varchar("created_at", { length: 64 }).notNull(),
  },
  (table) => [uniqueIndex("account_tokens_hash_unique").on(table.tokenHash)],
);
